### PR TITLE
fix input box styles and remove scrollbars

### LINKED ISSUE #7: Change the default scrollbar UI to something less noticeable
The default ones are too thick.
image

### PR DESCRIPTION
**Pull request by harsohailB**
**Changes:**

* Removed MUI styles from input and added custom styled-component styles
* Removed scrollbars completely

**Preview:**

Screen Shot 2021-04-24 at 12 38 02 PM

close #7

### CODE REVIEW

File: src/components/Selector/index.tsx [hunk 1]
```diff
@@ -25,20 +25,12 @@ const Selector = (props: {
 
 const Wrapper = styled.div`
   max-height: 400px;
-  overflow: scroll;
+  overflow-y: scroll;
+  overflow-x: hidden;
   width: 100%;
 
   ::-webkit-scrollbar {
-    width: 5px;
```
Comment (harsohailB) [inline src/components/Selector/index.tsx:32]: Make changes here if windows scrollbars are still an issue before merging @youup99

**Review by youup99 — APPROVED** [review]
